CREATE DATABASE projeto1;
USE projeto1;

CREATE TABLE sebo_usuarios (
    USR_ID INT AUTO_INCREMENT PRIMARY KEY,
    USR_NOME VARCHAR(60) NOT NULL,
    USR_EMAIL VARCHAR(45) NOT NULL UNIQUE,
    USR_SENHA VARCHAR(255) NOT NULL,
    USR_FOTO VARCHAR(255),
    USR_TELEFONE VARCHAR(45) NOT NULL
);

CREATE TABLE sebo_livros (
    LVR_ID INT AUTO_INCREMENT PRIMARY KEY,
    LVR_TITULO VARCHAR(60) NOT NULL,
    LVR_AUTOR VARCHAR(60) NOT NULL,
    LVR_SINOPSE VARCHAR(255) NOT NULL,
    LVR_FOTO VARCHAR(255) NOT NULL,
    LVR_DESCRICAO VARCHAR(255) NOT NULL,
    LVR_PRECO DECIMAL(10,2) NOT NULL,
    LVR_ID_USUARIO INT,
    CONSTRAINT FK_LIVROS_USUARIOS FOREIGN KEY (LVR_ID_USUARIO) REFERENCES sebo_usuarios(USR_ID)
);

CREATE TABLE sebo_desejos (
    DSJ_ID INT AUTO_INCREMENT PRIMARY KEY,
    DSJ_USR_ID INT NOT NULL,  
    DSJ_TITULO VARCHAR(255) NOT NULL,
    DSJ_AUTOR VARCHAR(255) NOT NULL,
    FOREIGN KEY (DSJ_USR_ID) REFERENCES sebo_usuarios(USR_ID)
);